# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ip_repo/floating_point_5/floating_point_5.xci
# IP: The module: 'floating_point_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ip_repo/floating_point_5/floating_point_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/ip_repo/floating_point_5/floating_point_5.xci
# IP: The module: 'floating_point_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ip_repo/floating_point_5/floating_point_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
