# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ip_repo/blk_mem_gen_7/blk_mem_gen_7.xci
# IP: The module: 'blk_mem_gen_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ip_repo/blk_mem_gen_7/blk_mem_gen_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_7'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/ip_repo/blk_mem_gen_7/blk_mem_gen_7.xci
# IP: The module: 'blk_mem_gen_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ip_repo/blk_mem_gen_7/blk_mem_gen_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
